source 'http://rubygems.org'

gem 'rails', '~> 4.2.0.rc1'
gem 'mailboxer', :path => '../../'
gem 'factory_girl'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem "sqlite3", :platform => [:ruby, :mswin, :mingw]
gem "jdbc-sqlite3", :platform => :jruby
